### ISSUE TITLE
Install success but jetforce not working

### ISSUE THREAD

**Issue by tiipiik** [michael-lazar/jetforce#79]
Hello,
I'm trying to install Jetforce on a Raspberry Pi zero with Raspbery Pi OS Lite (as known as old Raspbian). I have created a specific user wihout sudo rights to install Jetforce and install is successfull (virtual Python env) with no errors or warnings.
But when I try to use Jetforce I got those errors.
I'm using Python 3.9.
```
myuser@raspberrypi:~ $ jetforce -help
Traceback (most recent call last):
  File "/home/myuser/.local/bin/jetforce", line 5, in <module>
    from jetforce.__main__ import main
  File "/home/myuser/.local/lib/python3.9/site-packages/jetforce/__init__.py", line 13, in <module>
    from jetforce.protocol import GeminiProtocol
  File "/home/myuser/.local/lib/python3.9/site-packages/jetforce/protocol.py", line 18, in <module>
    from jetforce.tls import inspect_certificate
  File "/home/myuser/.local/lib/python3.9/site-packages/jetforce/tls.py", line 7, in <module>
    import OpenSSL.crypto
  File "/home/myuser/.local/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/myuser/.local/lib/python3.9/site-packages/OpenSSL/SSL.py", line 11, in <module>
    from OpenSSL._util import (
  File "/home/myuser/.local/lib/python3.9/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/myuser/.local/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "/home/myuser/.local/lib/python3.9/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.3: cannot open shared object file: No such file or directory
```
Any idea ?
Thanks

**Comment by tiipiik** [comment]
Thank you @mlazar-endear, it seems to join my personnal research. And it also seems to be relayed on Debian 11 not supporting OpenSSL 3. However, I've found a guide to upgrade OpenSSL from 1.1.1 to 3, I'll give it a try and tell you if I was successful !
